### ISSUE TITLE
ReminderBot seems to restart (drops registered reminders)

### ISSUE THREAD

**Issue by JayFoxRox** [mborgerson/reminderbot#1]
The bot running on XboxDev had some issues where it forgot existing reminders and started counting reminder indices from 0 again.

**Yesterday:**

* [...]
* Reminder 0 (after another low number): https://discordapp.com/channels/428359196719972353/428359408204906497/650791160545017891
* Reminder 0 (directly after 0): https://discordapp.com/channels/428359196719972353/428359408204906497/650791283195117577
* (Reminders 1 - 10 worked)
* Reminder 11: https://discordapp.com/channels/428359196719972353/428359408204906497/650791957668560896
* Reminder 0 (directly after 11): https://discordapp.com/channels/428359196719972353/428359408204906497/650793363888406528
* [...]

**Today:**

* Reminder 0: https://discordapp.com/channels/428359196719972353/428359408204906497/651050145365884928

---

Interestingly, the `!reminder` messages never seem to be dropped - so the reminder is probably already re-connected when the message comes in.
I'm not sure what server (/ environment) the bot currently runs on or if there are any logs. But there's definitely unreliability which makes the bot impractical to use.

I have also skimmed over the code but found nothing suspicious. The only thing I noticed was that this loop might not work correctly (this is purely speculation):

https://github.com/mborgerson/reminderbot/blob/223a4e57916c3c8c7a081490d9b303290d2db7d1/bot.py#L42-L51

I have not used `asyncio` yet, so I'm only guessing, but I could imagine that `self.reminders` is modified while the loop is being processed (which probably depends on the network speed). I'm not sure about the behaviour of the Python loop, but this could potentially cause trouble?

It could also just be a trivial exception which signals a failed message delivery or something.
Anyhow: This should be investigated.

**Comment by mborgerson** [comment]
Thanks for filing an issue. This appears to be a bug in the discord.py library, and looks to have been fixed since. The resetting to 0 was caused by the bot being auto restarted after crashing.

**Comment by JayFoxRox** [comment]
For the record, this was almost definitely https://github.com/Rapptz/discord.py/issues/2422
